/* ============================================================
   seed.js — Initial state and reference datasets (Contract)
   1-to-1 MRO industrial data matching DMP live architecture
   ============================================================ */
window.ContractSeed = (function () {

        const users = [
        {
            id: "u_cust1",
            name: "Demo Customer",
            role: "Procurement Specialist",
            type: "customer",
            email: "democustomer@dmpservice.org",
            company: "DMP Demo Company",
            department: "Central Procurement"
        },
        {
            id: "u_cust2",
            name: "Aisel Verdieva",
            role: "Category Manager (CAM)",
            type: "customer",
            email: "averdieva@dmpservice.org",
            company: "DMP Demo Company",
            department: "Contracts & Sourcing"
        },
        {
            id: "u_sup1",
            name: "Demo Supplier 1",
            role: "Vendor Admin",
            type: "supplier",
            email: "demosupplier1@dmpservice.org",
            company: "MRO AISEL",
            department: "Commercial Sales"
        },
        {
            id: "u_sup2",
            name: "Demo Supplier 2",
            role: "Account Manager",
            type: "supplier",
            email: "demosupplier2@dmpservice.org",
            company: "Asgar's Supplier Company",
            department: "Supply Operations"
        },
        {
            id: "u_sup3",
            name: "DSC Supplier Admin",
            role: "Sales Director",
            type: "supplier",
            email: "dsc@dmpservice.org",
            company: "DSC (demo supplier company)",
            department: "Distribution"
        },
        {
            id: "u_cust_john",
            name: "John Simpson",
            role: "Procurement Specialist",
            type: "customer",
            email: "jsimpson@socar.az",
            company: "SOCAR Upstream Operations",
            department: "Central Procurement"
        }
    ];

        const contracts = [
        {
            id: "CTR-2026-001",
            description: "test contract",
            external_id: "123123123",
            supplier: "MRO AISEL",
            supplier_id: "u_sup1",
            customer: "DMP Demo Company",
            customer_id: "u_cust1",
            procurement_contract_owner: "Aisel Verdieva",
            cam_name: "Aisel Verdieva",
            department_name: "Maintenance & Operations",
            region: "ANGR",
            valid_from: "2026-01-01",
            valid_to: "2028-12-31",
            approved_value: 12500000.00,
            spent_value: 3420000.00,
            currency: "USD",
            status: "Active",
            pricebook_count: 1,
            supplier_rating: {
                overall: 9.2,
                quality: 9.5,
                delivery: 8.8,
                commercial: 9.0,
                hse: 9.6,
                spend_weight: 0.21,
                criticality: "Tier 1 - Critical",
                due_diligence: "Approved"
            }
        },
        {
            id: "CTR-2026-002",
            description: "Test Description",
            external_id: "12345",
            supplier: "Asgar's Supplier Company",
            supplier_id: "u_sup2",
            customer: "DMP Demo Company",
            customer_id: "u_cust1",
            procurement_contract_owner: "Demo Customer",
            cam_name: "Demo Customer",
            department_name: "Drilling Operations",
            region: "AGTR",
            valid_from: "2026-02-15",
            valid_to: "2027-12-31",
            approved_value: 8400000.00,
            spent_value: 1950000.00,
            currency: "USD",
            status: "Active",
            pricebook_count: 1,
            supplier_rating: {
                overall: 8.9,
                quality: 9.1,
                delivery: 8.6,
                commercial: 8.8,
                hse: 9.2,
                spend_weight: 0.15,
                criticality: "Tier 1 - Critical",
                due_diligence: "Approved"
            }
        },
        {
            id: "CTR-2026-003",
            description: "Test",
            external_id: "12345",
            supplier: "Asgar's Supplier Company",
            supplier_id: "u_sup2",
            customer: "DMP Demo Company",
            customer_id: "u_cust1",
            procurement_contract_owner: "Demo Customer",
            cam_name: "Demo Customer",
            department_name: "Mechanical & Piping",
            region: "AGTR",
            valid_from: "2026-03-01",
            valid_to: "2028-02-28",
            approved_value: 4500000.00,
            spent_value: 820000.00,
            currency: "USD",
            status: "Active",
            pricebook_count: 1,
            supplier_rating: {
                overall: 9.4,
                quality: 9.6,
                delivery: 9.2,
                commercial: 9.3,
                hse: 9.7,
                spend_weight: 0.09,
                criticality: "Tier 2 - Important",
                due_diligence: "Approved"
            }
        },
        {
            id: "CTR-2026-004",
            description: "mro",
            external_id: "11",
            supplier: "MRO AISEL",
            supplier_id: "u_sup1",
            customer: "DMP Demo Company",
            customer_id: "u_cust1",
            procurement_contract_owner: "Aisel Verdieva",
            cam_name: "Aisel Verdieva",
            department_name: "Central Engineering",
            region: "ANGR",
            valid_from: "2026-01-10",
            valid_to: "2029-01-10",
            approved_value: 48000000.00,
            spent_value: 11200000.00,
            currency: "USD",
            status: "Active",
            pricebook_count: 3,
            supplier_rating: {
                overall: 9.1,
                quality: 9.3,
                delivery: 8.7,
                commercial: 8.9,
                hse: 9.5,
                spend_weight: 0.28,
                criticality: "Tier 1 - Critical",
                due_diligence: "Approved"
            }
        },
        {
            id: "CTR-2026-005",
            description: "test contract",
            external_id: "10",
            supplier: "DSC (demo supplier company)",
            supplier_id: "u_sup3",
            customer: "DMP Demo Company",
            customer_id: "u_cust1",
            procurement_contract_owner: "Aisel Verdieva",
            cam_name: "Aisel Verdieva",
            department_name: "Instrumentation",
            region: "ANGR",
            valid_from: "2026-04-01",
            valid_to: "2027-04-01",
            approved_value: 2100000.00,
            spent_value: 450000.00,
            currency: "USD",
            status: "Upcoming",
            pricebook_count: 0,
            supplier_rating: {
                overall: 8.6,
                quality: 8.8,
                delivery: 8.4,
                commercial: 8.5,
                hse: 9.0,
                spend_weight: 0.05,
                criticality: "Tier 3 - Standard",
                due_diligence: "Approved"
            }
        },
        {
            id: "CTR-2026-006",
            description: "MRO AISEL Master Service Agreement",
            external_id: "CTR-AZE-2026-9901",
            supplier: "MRO AISEL",
            supplier_id: "u_sup1",
            customer: "DMP Demo Company",
            customer_id: "u_cust1",
            procurement_contract_owner: "Demo Customer",
            cam_name: "Aisel Verdieva",
            department_name: "Maintenance & Reliability",
            region: "Caspian Offshore / Baku",
            valid_from: "2026-01-01",
            valid_to: "2028-12-31",
            approved_value: 68234115.00,
            spent_value: 14328950.00,
            currency: "USD",
            status: "Active",
            pricebook_count: 3,
            supplier_rating: {
                overall: 9.2,
                quality: 9.5,
                delivery: 8.8,
                commercial: 9.0,
                hse: 9.6,
                spend_weight: 0.21,
                criticality: "Tier 1 - Critical",
                due_diligence: "Approved"
            }
        },
        {
            id: "CTR-2025-089",
            description: "Site Consumables, Hardware & PPE Framework",
            external_id: "CTR-AZE-2025-3312",
            supplier: "Global MRO Trading FZE",
            supplier_id: "u_sup4",
            customer: "SOCAR Upstream Operations",
            customer_id: "u_cust1",
            procurement_contract_owner: "John Simpson",
            cam_name: "Aysel Karimova",
            department_name: "HSE & General Services",
            region: "Baku Central Warehouse",
            valid_from: "2025-01-01",
            valid_to: "2025-12-31",
            approved_value: 3400000.00,
            spent_value: 3389000.00,
            currency: "USD",
            status: "Expired",
            pricebook_count: 1,
            supplier_rating: {
                overall: 8.4,
                quality: 8.5,
                delivery: 8.2,
                commercial: 8.6,
                hse: 9.0,
                spend_weight: 0.04,
                criticality: "Tier 3 - Standard",
                due_diligence: "Approved"
            }
        },
        {
            id: "CTR-2026-015",
            description: "Substation Switchgear & Transformers Maintenance",
            external_id: "CTR-AZE-2026-4409",
            supplier: "Baku Industrial Supplies LLC",
            supplier_id: "u_sup1",
            customer: "SOCAR Upstream Operations",
            customer_id: "u_cust1",
            procurement_contract_owner: "John Simpson",
            cam_name: "Aysel Karimova",
            department_name: "Electrical & Instrumentation",
            region: "Caspian Offshore / Baku",
            valid_from: "2026-11-01",
            valid_to: "2029-10-31",
            approved_value: 12000000.00,
            spent_value: 0.00,
            currency: "USD",
            status: "Upcoming",
            pricebook_count: 1,
            supplier_rating: {
                overall: 9.2,
                quality: 9.5,
                delivery: 8.8,
                commercial: 9.0,
                hse: 9.6,
                spend_weight: 0.12,
                criticality: "Tier 1 - Critical",
                due_diligence: "Approved"
            }
        }
    ];

    const pricebooks = [
        {
            id: "PB-2026-001-A",
            contract_id: "CTR-2026-001",
            pricebook_number: "PB-001-ROTATING",
            external_pricebook_number: "EXT-PB-001",
            description: "Mechanical Rotating Equipment & Bearings Price Agreement",
            currency: "USD",
            status: "Active",
            items_count: 5,
            created_at: "2026-01-05"
        },
        {
            id: "PB-2026-001-B",
            contract_id: "CTR-2026-001",
            pricebook_number: "PB-002-GASKETS",
            external_pricebook_number: "EXT-PB-002",
            description: "Piping Gaskets & High Tensile Fasteners Catalogue",
            currency: "USD",
            status: "Active",
            items_count: 3,
            created_at: "2026-01-12"
        },
        {
            id: "PB-2026-001-C",
            contract_id: "CTR-2026-001",
            pricebook_number: "PB-003-BREAKDOWN",
            external_pricebook_number: "EXT-PB-003",
            description: "Emergency Breakdown Spares Call-Off Rates",
            currency: "USD",
            status: "Draft",
            items_count: 2,
            created_at: "2026-02-01"
        },
        {
            id: "PB-2026-002-A",
            contract_id: "CTR-2026-002",
            pricebook_number: "PB-101-DRILLBITS",
            external_pricebook_number: "EXT-PB-101",
            description: "Drilling Bits & Premium Tubulars Agreement",
            currency: "USD",
            status: "Active",
            items_count: 4,
            created_at: "2026-02-20"
        },
        {
            id: "PB-2026-002-B",
            contract_id: "CTR-2026-002",
            pricebook_number: "PB-102-PACKERS",
            external_pricebook_number: "EXT-PB-102",
            description: "Completion Packers & Liner Hangers",
            currency: "USD",
            status: "Active",
            items_count: 2,
            created_at: "2026-03-01"
        },
        {
            id: "PB-2026-003-A",
            contract_id: "CTR-2026-003",
            pricebook_number: "PB-201-VALVES",
            external_pricebook_number: "EXT-PB-201",
            description: "Ball & Check Valves Class 150-1500",
            currency: "USD",
            status: "Active",
            items_count: 4,
            created_at: "2026-03-05"
        },
        {
            id: "PB-2025-089-A",
            contract_id: "CTR-2025-089",
            pricebook_number: "PB-301-PPE",
            external_pricebook_number: "EXT-PB-301",
            description: "General Consumables Standard Price List",
            currency: "USD",
            status: "Disabled",
            items_count: 3,
            created_at: "2025-01-10"
        },
        {
            id: "PB-2026-015-A",
            contract_id: "CTR-2026-015",
            pricebook_number: "PB-401-ELECTRICAL",
            external_pricebook_number: "EXT-PB-401",
            description: "Electrical Maintenance Rates 2026",
            currency: "USD",
            status: "Active",
            items_count: 3,
            created_at: "2026-11-05"
        }
    ];

    const line_items = [
        {
            id: "itm_001",
            pricebook_id: "PB-2026-001-A",
            dmp_id: "DMP-MRO-00109",
            photo: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=120&auto=format&fit=crop&q=60",
            status: "Approved",
            supplier_part_no: "SKF-6307-2RS1",
            material_service_no: "10029381",
            product_type: "Goods",
            uom: "EA",
            customer_short_description: "BEARING,BALL:6307-2RS1",
            customer_long_description: "BEARING,BALL:6307-2RS1 DEEP GROOVE,BORE:35MM,OD:80MM,WIDTH:21MM,SEALS:RUBBER BOTH SIDES,CLEARANCE:C3",
            supplier_description: "Deep groove ball bearing 6307-2RS1/C3 with synthetic rubber seals and premium grease fill",
            manufacturer_name: "SKF AB",
            manufacturer_part_no: "6307-2RS1/C3",
            unit_price: 185.00,
            currency: "USD",
            lead_time_days: 14,
            incoterms_key: "DDP",
            incoterms_location: "Baku Central Warehouse",
            unspsc: "31171504",
            unspsc_title: "Ball bearings",
            valid_from: "2026-01-01",
            valid_to: "2028-12-31",
            moq: 1,
            order_multiple: 1,
            price_validity: "Fixed 2 Years",
            country_of_origin: "Sweden",
            customs_tariff_hs: "8482.10.90",
            hazardous_material: "No",
            shelf_life_months: 60,
            warranty_months: 24,
            spec_sheet_url: "docs/spec_skf_6307.pdf",
            sds_url: "docs/sds_skf_6307.pdf",
            discount_tier: "5% for qty > 50",
            indexation_clause: "LME Steel Producer Price Index",
            price_type: "Firm Fixed",
            created_date: "2026-01-05",
            modified_by: "John Simpson"
        },
        {
            id: "itm_002",
            pricebook_id: "PB-2026-001-A",
            dmp_id: "DMP-MRO-00110",
            photo: "https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=120&auto=format&fit=crop&q=60",
            status: "Approved",
            supplier_part_no: "SKF-22220-EK",
            material_service_no: "10029382",
            product_type: "Goods",
            uom: "EA",
            customer_short_description: "BEARING,ROLLER,SPHERICAL:22220-EK",
            customer_long_description: "BEARING,ROLLER,SPHERICAL:22220-EK TAPERED BORE 1:12,BORE:100MM,OD:180MM,WIDTH:46MM",
            supplier_description: "Spherical roller bearing with tapered bore 22220 EK/C3",
            manufacturer_name: "SKF AB",
            manufacturer_part_no: "22220-EK/C3",
            unit_price: 495.00,
            currency: "USD",
            lead_time_days: 21,
            incoterms_key: "DDP",
            incoterms_location: "Baku Central Warehouse",
            unspsc: "31171505",
            unspsc_title: "Roller bearings",
            valid_from: "2026-01-01",
            valid_to: "2028-12-31",
            moq: 1,
            order_multiple: 1,
            price_validity: "Fixed 2 Years",
            country_of_origin: "Germany",
            customs_tariff_hs: "8482.30.00",
            hazardous_material: "No",
            shelf_life_months: 60,
            warranty_months: 24,
            spec_sheet_url: "docs/spec_skf_22220.pdf",
            sds_url: "docs/sds_skf_22220.pdf",
            discount_tier: "7% for qty > 20",
            indexation_clause: "LME Steel Producer Price Index",
            price_type: "Firm Fixed",
            created_date: "2026-01-05",
            modified_by: "John Simpson"
        },
        {
            id: "itm_003",
            pricebook_id: "PB-2026-001-A",
            dmp_id: "DMP-MRO-00145",
            photo: "https://images.unsplash.com/photo-1504917599217-d4dc5ebe6122?w=120&auto=format&fit=crop&q=60",
            status: "Approved",
            supplier_part_no: "BURG-M7N-50",
            material_service_no: "10029383",
            product_type: "Goods",
            uom: "SET",
            customer_short_description: "SEAL,MECHANICAL:M7N/50-Q1Q1VGG",
            customer_long_description: "SEAL,MECHANICAL:M7N/50-Q1Q1VGG SHAFT:50MM,CARTRIDGE WAVE SPRING,SIC/SIC/FKM",
            supplier_description: "EagleBurgmann standard mechanical seal M7N wave spring 50mm shaft",
            manufacturer_name: "EagleBurgmann",
            manufacturer_part_no: "M7N/50-00",
            unit_price: 1280.00,
            currency: "USD",
            lead_time_days: 30,
            incoterms_key: "DDP",
            incoterms_location: "Baku Central Warehouse",
            unspsc: "31181504",
            unspsc_title: "Mechanical seals",
            valid_from: "2026-01-01",
            valid_to: "2028-12-31",
            moq: 1,
            order_multiple: 1,
            price_validity: "Fixed 1 Year",
            country_of_origin: "Germany",
            customs_tariff_hs: "8484.20.00",
            hazardous_material: "No",
            shelf_life_months: 36,
            warranty_months: 18,
            spec_sheet_url: "docs/spec_burgmann_m7n.pdf",
            sds_url: "",
            discount_tier: "None",
            indexation_clause: "Fixed",
            price_type: "Firm Fixed",
            created_date: "2026-01-08",
            modified_by: "John Simpson"
        },
        {
            id: "itm_004",
            pricebook_id: "PB-2026-001-A",
            dmp_id: "DMP-MRO-00188",
            photo: "https://images.unsplash.com/photo-1581092162384-8987c1d64718?w=120&auto=format&fit=crop&q=60",
            status: "Pending",
            supplier_part_no: "FALK-WRAP-1040G",
            material_service_no: "10029384",
            product_type: "Goods",
            uom: "EA",
            customer_short_description: "COUPLING,ELASTOMER:FALK WRAPFLEX 1040G",
            customer_long_description: "COUPLING,ELASTOMER:FALK WRAPFLEX 1040G TORQUE:550NM,URETHANE ELEMENT,BORE:45MM",
            supplier_description: "Rexnord Falk Wrapflex elastomeric coupling size 1040G replacement element",
            manufacturer_name: "Rexnord / Falk",
            manufacturer_part_no: "1040G-EL",
            unit_price: 340.00,
            currency: "USD",
            lead_time_days: 18,
            incoterms_key: "DDP",
            incoterms_location: "Baku Central Warehouse",
            unspsc: "31171501",
            unspsc_title: "Couplings",
            valid_from: "2026-02-01",
            valid_to: "2028-12-31",
            moq: 2,
            order_multiple: 2,
            price_validity: "Fixed 1 Year",
            country_of_origin: "USA",
            customs_tariff_hs: "8483.60.80",
            hazardous_material: "No",
            shelf_life_months: 48,
            warranty_months: 12,
            spec_sheet_url: "docs/spec_wrapflex_1040g.pdf",
            sds_url: "",
            discount_tier: "10% for qty > 10",
            indexation_clause: "Fixed",
            price_type: "Firm Fixed",
            created_date: "2026-02-01",
            modified_by: "Rashad Aliyev"
        },
        {
            id: "itm_005",
            pricebook_id: "PB-2026-001-A",
            dmp_id: "DMP-MRO-00195",
            photo: "https://images.unsplash.com/photo-1581092580497-e0d23cbdf1dc?w=120&auto=format&fit=crop&q=60",
            status: "Approved",
            supplier_part_no: "OPTIBELT-SPB-2800",
            material_service_no: "10029385",
            product_type: "Goods",
            uom: "EA",
            customer_short_description: "BELT,V:SPB 2800 RED POWER",
            customer_long_description: "BELT,V:SPB 2800 RED POWER 3 HIGH PERFORMANCE WEDGE BELT,LENGTH:2800MM,ANTISTATIC ISO 1813",
            supplier_description: "Optibelt Red Power 3 SPB 2800 maintenance-free wedge belt",
            manufacturer_name: "Optibelt GmbH",
            manufacturer_part_no: "SPB-2800-RP3",
            unit_price: 78.50,
            currency: "USD",
            lead_time_days: 7,
            incoterms_key: "DDP",
            incoterms_location: "Baku Central Warehouse",
            unspsc: "26111801",
            unspsc_title: "V-belts",
            valid_from: "2026-01-01",
            valid_to: "2028-12-31",
            moq: 5,
            order_multiple: 5,
            price_validity: "Fixed 2 Years",
            country_of_origin: "Germany",
            customs_tariff_hs: "4010.32.00",
            hazardous_material: "No",
            shelf_life_months: 72,
            warranty_months: 24,
            spec_sheet_url: "docs/spec_optibelt_spb.pdf",
            sds_url: "",
            discount_tier: "12% for qty > 50",
            indexation_clause: "Rubber Index",
            price_type: "Firm Fixed",
            created_date: "2026-01-05",
            modified_by: "John Simpson"
        },
        {
            id: "itm_006",
            pricebook_id: "PB-2026-001-B",
            dmp_id: "DMP-MRO-00210",
            photo: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=120&auto=format&fit=crop&q=60",
            status: "Approved",
            supplier_part_no: "FLEX-CG-6-300",
            material_service_no: "10029390",
            product_type: "Goods",
            uom: "EA",
            customer_short_description: "GASKET,SPIRAL WOUND:6IN 300LB ASME B16.20",
            customer_long_description: "GASKET,SPIRAL WOUND:6IN 300LB ASME B16.20 STYLE CG,316L WINDING / GRAPHITE FILLER,CS OUTER RING",
            supplier_description: "Flexitallic Style CG spiral wound gasket 6 inch Class 300 with flexible graphite",
            manufacturer_name: "Flexitallic",
            manufacturer_part_no: "CG-060-300-316L/FG",
            unit_price: 42.00,
            currency: "USD",
            lead_time_days: 10,
            incoterms_key: "DDP",
            incoterms_location: "Baku Central Warehouse",
            unspsc: "31181502",
            unspsc_title: "Gaskets",
            valid_from: "2026-01-12",
            valid_to: "2028-12-31",
            moq: 10,
            order_multiple: 5,
            price_validity: "Fixed 2 Years",
            country_of_origin: "United Kingdom",
            customs_tariff_hs: "8484.10.00",
            hazardous_material: "No",
            shelf_life_months: 120,
            warranty_months: 24,
            spec_sheet_url: "docs/spec_flex_cg.pdf",
            sds_url: "",
            discount_tier: "15% for qty > 100",
            indexation_clause: "Fixed",
            price_type: "Firm Fixed",
            created_date: "2026-01-12",
            modified_by: "John Simpson"
        },
        {
            id: "itm_007",
            pricebook_id: "PB-2026-001-B",
            dmp_id: "DMP-MRO-00215",
            photo: "https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=120&auto=format&fit=crop&q=60",
            status: "Approved",
            supplier_part_no: "FAST-B7-M24-180",
            material_service_no: "10029391",
            product_type: "Goods",
            uom: "SET",
            customer_short_description: "STUD BOLT:ASTM A193 B7 M24X180 WITH 2 NUTS 2H",
            customer_long_description: "STUD BOLT:ASTM A193 B7 M24X180 WITH 2 NUTS ASTM A194 2H,XYLAN PTFE COATING GREEN,ISO 965 METRIC",
            supplier_description: "High integrity stud bolt set B7 M24x180mm PTFE fluoropolymer coated",
            manufacturer_name: "Beck Industries",
            manufacturer_part_no: "B7-M24-180-XYL",
            unit_price: 18.50,
            currency: "USD",
            lead_time_days: 7,
            incoterms_key: "DDP",
            incoterms_location: "Baku Central Warehouse",
            unspsc: "31161601",
            unspsc_title: "Bolts",
            valid_from: "2026-01-12",
            valid_to: "2028-12-31",
            moq: 20,
            order_multiple: 10,
            price_validity: "Fixed 2 Years",
            country_of_origin: "France",
            customs_tariff_hs: "7318.15.20",
            hazardous_material: "No",
            shelf_life_months: 120,
            warranty_months: 36,
            spec_sheet_url: "docs/spec_stud_b7.pdf",
            sds_url: "",
            discount_tier: "10% for qty > 200",
            indexation_clause: "Fixed",
            price_type: "Firm Fixed",
            created_date: "2026-01-12",
            modified_by: "John Simpson"
        },
        {
            id: "itm_008",
            pricebook_id: "PB-2026-003-A",
            dmp_id: "DMP-MRO-00301",
            photo: "https://images.unsplash.com/photo-1504917599217-d4dc5ebe6122?w=120&auto=format&fit=crop&q=60",
            status: "Approved",
            supplier_part_no: "CAM-BALL-4-600",
            material_service_no: "10034401",
            product_type: "Goods",
            uom: "EA",
            customer_short_description: "VALVE,BALL:4IN 600LB RF TRUNNION API 6D",
            customer_long_description: "VALVE,BALL:4IN 600LB RF TRUNNION API 6D BODY:A216 WCB,TRIM:316SS,SEATS:DEVLON V,FIRE SAFE API 607",
            supplier_description: "Cameron fully welded trunnion mounted ball valve 4 inch Class 600 flanged RF",
            manufacturer_name: "Cameron / SLB",
            manufacturer_part_no: "TBV-04-600-WCB",
            unit_price: 4850.00,
            currency: "USD",
            lead_time_days: 45,
            incoterms_key: "DDP",
            incoterms_location: "Shah Deniz Platform",
            unspsc: "40141607",
            unspsc_title: "Ball valves",
            valid_from: "2026-03-01",
            valid_to: "2028-02-28",
            moq: 1,
            order_multiple: 1,
            price_validity: "Fixed 18 Months",
            country_of_origin: "Italy",
            customs_tariff_hs: "8481.80.81",
            hazardous_material: "No",
            shelf_life_months: 60,
            warranty_months: 36,
            spec_sheet_url: "docs/spec_cameron_tbv.pdf",
            sds_url: "",
            discount_tier: "None",
            indexation_clause: "Fixed",
            price_type: "Firm Fixed",
            created_date: "2026-03-05",
            modified_by: "Marco Rossi"
        }
    ];

    const kpis = [
        {
            id: "kpi_1",
            contract_id: "CTR-2026-001",
            kpi_name: "On-Time In-Full Delivery (OTIF)",
            target_agreed: 95.0,
            unit: "%",
            frequency: "Monthly",
            category: "Delivery",
            monthly_values: [96.2, 94.8, 97.1, 95.5, 96.0, 95.8, 97.2, 96.4, null, null, null, null],
            ytd_average: 96.1,
            status: "Achieved"
        },
        {
            id: "kpi_2",
            contract_id: "CTR-2026-001",
            kpi_name: "Material Quality Acceptance Rate",
            target_agreed: 99.0,
            unit: "%",
            frequency: "Monthly",
            category: "Quality",
            monthly_values: [99.5, 98.9, 99.8, 100.0, 99.2, 99.7, 99.4, 99.6, null, null, null, null],
            ytd_average: 99.5,
            status: "Achieved"
        },
        {
            id: "kpi_3",
            contract_id: "CTR-2026-001",
            kpi_name: "Emergency Breakdown RFQ Response Time",
            target_agreed: 24.0,
            unit: "Hours",
            frequency: "Monthly",
            category: "Commercial",
            monthly_values: [18.0, 22.0, 16.0, 26.0, 19.0, 14.0, 20.0, 18.0, null, null, null, null],
            ytd_average: 19.1,
            status: "Achieved"
        },
        {
            id: "kpi_4",
            contract_id: "CTR-2026-001",
            kpi_name: "HSE Incident-Free Delivery Rate",
            target_agreed: 100.0,
            unit: "%",
            frequency: "Monthly",
            category: "HSE",
            monthly_values: [100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, null, null, null, null],
            ytd_average: 100.0,
            status: "Achieved"
        }
    ];

    const performance_reports = [
        {
            id: "26",
            report_number: "26",
            contract_id: "CTR-2026-001",
            type: "PIP",
            title: "sqsqs",
            status: "Open",
            priority: "Medium",
            actions: "0/0",
            progress: 0,
            issue_date: "2026-04-04",
            deadline: "2026-04-20",
            closed_date: "-"
        },
        {
            id: "25",
            report_number: "25",
            contract_id: "CTR-2026-001",
            type: "NCR",
            title: "Not right product",
            status: "Open",
            priority: "High",
            actions: "0/1",
            progress: 0,
            issue_date: "2026-04-02",
            deadline: "2026-04-22",
            closed_date: "-"
        },
        {
            id: "24",
            report_number: "24",
            contract_id: "CTR-2026-001",
            type: "NCR",
            title: "no dilivery",
            status: "Open",
            priority: "Medium",
            actions: "0/0",
            progress: 0,
            issue_date: "2026-04-13",
            deadline: "2026-04-21",
            closed_date: "-"
        },
        {
            id: "23",
            report_number: "23",
            contract_id: "CTR-2026-001",
            type: "NCR",
            title: "Issue",
            status: "Resolved",
            priority: "Medium",
            actions: "0/0",
            progress: 0,
            issue_date: "2026-04-02",
            deadline: "2026-04-22",
            closed_date: "2026-04-13"
        }
    ];

    const ctr_requests = [
        {
            id: "83",
            status: "Closed",
            required_action_by: "Procurement",
            items_count: 81,
            approved_count: 81,
            pending_count: 0,
            disabled_count: 0,
            declined_count: 0,
            supplier_name: "MRO AISEL",
            currency: "USD",
            assigned_to: "Aisel Verdieva",
            created_at: "2026-04-27 07:06:48",
            updated_at: "2026-04-27 07:08:00",
            contract_description: "test contract",
            pricebook_number: "28",
            external_pricebook_number: "1234512",
            requested_by: "Aisel TEST",
            cam_name: "Aisel Verdieva",
            contract_owner_name: "Aisel Verdieva"
        },
        {
            id: "82",
            status: "Closed",
            required_action_by: "CAM",
            items_count: 81,
            approved_count: 81,
            pending_count: 0,
            disabled_count: 0,
            declined_count: 0,
            supplier_name: "MRO AISEL",
            currency: "USD",
            assigned_to: "Aisel Verdieva",
            created_at: "2026-04-27 07:02:02",
            updated_at: "2026-04-27 07:06:16",
            contract_description: "test contract",
            pricebook_number: "28",
            external_pricebook_number: "1234512",
            requested_by: "Aisel TEST",
            cam_name: "Aisel Verdieva",
            contract_owner_name: "Aisel Verdieva"
        },
        {
            id: "81",
            status: "Closed",
            required_action_by: "Procurement",
            items_count: 99,
            approved_count: 99,
            pending_count: 0,
            disabled_count: 0,
            declined_count: 0,
            supplier_name: "MRO AISEL",
            currency: "USD",
            assigned_to: "Aisel Verdieva",
            created_at: "2026-04-27 07:06:23",
            updated_at: "2026-04-27 07:07:18",
            contract_description: "test contract",
            pricebook_number: "28",
            external_pricebook_number: "1234512",
            requested_by: "Aisel TEST",
            cam_name: "Aisel Verdieva",
            contract_owner_name: "Aisel Verdieva"
        },
        {
            id: "80",
            status: "Closed",
            required_action_by: "CAM",
            items_count: 99,
            approved_count: 99,
            pending_count: 0,
            disabled_count: 0,
            declined_count: 0,
            supplier_name: "MRO AISEL",
            currency: "USD",
            assigned_to: "Aisel Verdieva",
            created_at: "2026-04-27 07:01:48",
            updated_at: "2026-04-27 07:06:23",
            contract_description: "test contract",
            pricebook_number: "28",
            external_pricebook_number: "1234512",
            requested_by: "Aisel TEST",
            cam_name: "Aisel Verdieva",
            contract_owner_name: "Aisel Verdieva"
        },
        {
            id: "79",
            status: "Closed",
            required_action_by: "Procurement",
            items_count: 1,
            approved_count: 1,
            pending_count: 0,
            disabled_count: 0,
            declined_count: 0,
            supplier_name: "MRO AISEL",
            currency: "USD",
            assigned_to: "Aisel Verdieva",
            created_at: "2026-04-27 07:01:48",
            updated_at: "2026-04-27 07:08:08",
            contract_description: "test contract",
            pricebook_number: "28",
            external_pricebook_number: "1234512",
            requested_by: "Aisel TEST",
            cam_name: "Aisel Verdieva",
            contract_owner_name: "Aisel Verdieva"
        },
        {
            id: "78",
            status: "Closed",
            required_action_by: "Procurement",
            items_count: 179,
            approved_count: 179,
            pending_count: 0,
            disabled_count: 0,
            declined_count: 0,
            supplier_name: "Asgar's Supplier Company",
            currency: "AZN",
            assigned_to: "Demo Customer",
            created_at: "2026-04-24 06:14:17",
            updated_at: "2026-04-24 06:28:58",
            contract_description: "Test Description",
            pricebook_number: "25",
            external_pricebook_number: "EXT-25",
            requested_by: "Demo Customer",
            cam_name: "Demo Customer",
            contract_owner_name: "Demo Customer"
        },
        {
            id: "77",
            status: "Closed",
            required_action_by: "CAM",
            items_count: 181,
            approved_count: 181,
            pending_count: 0,
            disabled_count: 0,
            declined_count: 0,
            supplier_name: "Asgar's Supplier Company",
            currency: "AZN",
            assigned_to: "Demo Customer",
            created_at: "2026-04-24 06:11:05",
            updated_at: "2026-04-24 06:14:17",
            contract_description: "Test Description",
            pricebook_number: "25",
            external_pricebook_number: "EXT-25",
            requested_by: "Demo Customer",
            cam_name: "Demo Customer",
            contract_owner_name: "Demo Customer"
        },
        {
            id: "76",
            status: "Open",
            required_action_by: "Procurement",
            items_count: 1,
            approved_count: 0,
            pending_count: 1,
            disabled_count: 0,
            declined_count: 0,
            supplier_name: "Vendor A",
            currency: "USD",
            assigned_to: "Demo Customer",
            created_at: "2026-04-16 10:15:45",
            updated_at: "2026-04-16 10:15:45",
            contract_description: "Vendor Agreement",
            pricebook_number: "19",
            external_pricebook_number: "EXT-19",
            requested_by: "Vendor A",
            cam_name: "Demo Customer",
            contract_owner_name: "Demo Customer"
        }
    ];

    const ctr_items = [
        {
            id: "ctr_itm_1",
            request_id: "83",
            item_no: 1,
            request_type: "NEW",
            review: "Approved",
            has_comments: true,
            has_attachments: true,
            supplier_part_no: "CW290057_206",
            material_service_no: "11075489",
            part_extension: "",
            product_type: "MATERIAL",
            uom: "EA",
            manufacturer_name: "Schneider Electric",
            unspsc_code: "39121601",
            unit_price: 185.00,
            price_change: "0%"
        },
        {
            id: "ctr_itm_2",
            request_id: "83",
            item_no: 2,
            request_type: "NEW",
            review: "Approved",
            has_comments: true,
            has_attachments: true,
            supplier_part_no: "CW290057_208",
            material_service_no: "36116960",
            part_extension: "",
            product_type: "MATERIAL",
            uom: "EA",
            manufacturer_name: "Schneider Electric",
            unspsc_code: "39121601",
            unit_price: 240.00,
            price_change: "0%"
        },
        {
            id: "ctr_itm_3",
            request_id: "83",
            item_no: 3,
            request_type: "NEW",
            review: "Approved",
            has_comments: true,
            has_attachments: true,
            supplier_part_no: "CW290057_209",
            material_service_no: "11044906",
            part_extension: "",
            product_type: "MATERIAL",
            uom: "EA",
            manufacturer_name: "ABB",
            unspsc_code: "39121601",
            unit_price: 310.00,
            price_change: "0%"
        },
        {
            id: "ctr_itm_4",
            request_id: "83",
            item_no: 4,
            request_type: "NEW",
            review: "Approved",
            has_comments: true,
            has_attachments: true,
            supplier_part_no: "CW290057_21",
            material_service_no: "11027996",
            part_extension: "",
            product_type: "MATERIAL",
            uom: "EA",
            manufacturer_name: "ABB",
            unspsc_code: "39121601",
            unit_price: 95.00,
            price_change: "0%"
        },
        {
            id: "ctr_itm_5",
            request_id: "83",
            item_no: 5,
            request_type: "NEW",
            review: "Approved",
            has_comments: true,
            has_attachments: true,
            supplier_part_no: "CW290057_210",
            material_service_no: "36070852",
            part_extension: "",
            product_type: "MATERIAL",
            uom: "EA",
            manufacturer_name: "Siemens",
            unspsc_code: "39121601",
            unit_price: 520.00,
            price_change: "0%"
        }
    ];

    return {
        initialState: function () {
            return {
                currentUser: users[0].id,
                session: {
                    lang: "en",
                    user: users[0].id
                },
                users: users,
                contracts: contracts,
                pricebooks: pricebooks,
                line_items: line_items,
                kpis: kpis,
                performance_reports: performance_reports,
                ctr_requests: ctr_requests,
                ctr_items: ctr_items,
                notifications: [
                    {
                        id: "notif_1",
                        title: "Pricebook CTR Request Submitted",
                        body: "Baku Industrial Supplies LLC requested indexation price adjustment on CTR-2026-001.",
                        read: false,
                        ts: Date.now() - 3600000 * 4,
                        contractId: "CTR-2026-001"
                    },
                    {
                        id: "notif_2",
                        title: "KPI Target Fulfilled",
                        body: "August 2026 Quality Acceptance Rate reached 99.6% (Target: 99%).",
                        read: true,
                        ts: Date.now() - 86400000 * 2,
                        contractId: "CTR-2026-001"
                    },
                    {
                        id: "notif_3",
                        title: "Performance Report Resolved",
                        body: "NCR-2026-001 regarding gasket dimensions marked resolved by Quality Lead.",
                        read: true,
                        ts: Date.now() - 86400000 * 5,
                        contractId: "CTR-2026-001"
                    }
                ],
                __savedAt: Date.now()
            };
        }
    };
})();
